[package]
name = "realtime-db-mongodb"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
realtime-core = { path = "../realtime-core" }
tokio = { workspace = true }
async-trait = { workspace = true }
mongodb = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
bytes = { workspace = true }
tracing = { workspace = true }
futures = { workspace = true }

[lints]
workspace = true
